### ISSUE TITLE
Can you add all Unicode Chinese Characters in CJK Unified Ideographs area to this game?

### ISSUE THREAD

**Issue by loader3229** [spotky1004/Chinese-Character-Alchemy#1]
Can you add all Unicode Chinese Characters in CJK Unified Ideographs area to this game?
I an trying to merge character 惊(U+60CA) in CJK Unified Ideographs area from parts 忄(U+5FC4) and 京(U+4EAC), but it fails. The character 惊(U+60CA) is not in data.txt.

**Comment by loader3229** [comment]
Other examples: 辻(U+8FBB), 扒(U+6252), 贝(U+8D1D), etc.

**Comment by spotky1004** [comment]
Thank you for your contribution. I'm going to add 13437 new characters from CJK Unified Ideographs area!

**Comment by loader3229** [comment]
Also, add characters from CJK Unified Ideographs Extension A area as well!
